#TODO: figure out what to replace "target" with in maventest & autodeploy
#TODO: figure out what to put in "image" for android build/test
stages:
  - update
  - mavenbuild
  - maventest
  - autodeploy
  - androidbuild
  - androidtest

updateBackend:
  stage: update
  tags: 
    - --LFT-backend
  script:
    # - 'which ssh-agent || (apt-get update -y && apt-get install openssh-client -y)'
    # eval $(ssh-agent -s)
    # echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    # mkdir -p ~/.ssh
    # chmod 700 ~/.ssh
    # echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    # chmod 644 ~/.ssh/known_hosts
    - cd Backend/LFT
  
maven-build:
  stage: mavenbuild
  tags:
    - --LFT-backend
  script:
    - cd Backend/LFT
    - export M2_HOME=/usr/local/src/apache-maven
    - export PATH=${M2_HOME}/bin:${PATH}
    - echo $PATH
    - $M2_HOME/bin/mvn package -B

maven-test:
  stage: maventest
  tags:
    - --LFT-backend
  script:
    - cd Backend/LFT
    - mvn clean install
  artifacts:
    paths:
      - Backend/LFT/target/*.jar

auto-deploy:
  stage: autodeploy
  tags:
    - --LFT-backend
  script:
    - cd Backend/LFT
    #- mvn package
    #- sudo mv target/*.jar /target/web-demo.jar 
    #- sudo systemctl stop systemd-web-demo
    #- sudo systemctl start systemd-web-demo

android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/lft_lookingforteam/gradlew
  tags:
    - --LFT-android
  script:
    - cd Frontend/lft_lookingforteam
    - ./gradlew assemble
  artifacts:
    paths:
      - Frontend/lft_lookingforteam/app/build/outputs/

android-test:
  image: javiersantos/android-ci:latest
  stage: androidtest
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./Frontend/lft_lookingforteam/gradlew
  tags:
    - --LFT-android
  script:
    - cd Frontend/lft_lookingforteam
    #- ./gradlew test
    #TODO: create Android unit tests